Let backslashToForwardSlash handle arrays of paths
I got an error when running npm run rig-init:

TypeError: path.replace is not a function

Turns out the function sometimes receives arrays of paths, so I added support for that.

Also made the replacement into an arrow function to avoid repetition of code.